[theme]
base="light"
primaryColor="#3182bd"
backgroundColor="#e3f0fc"
seconadaryBackgroundColor="#eef2f5"
textColor="#2a2a31"
font="sans-serif"
headingFont="serif"
codeFont="monospace"
baseFontSize=17